### PR TITLE
Arch migrate

### PR DESCRIPTION
**Pull request by martin-g**
This is a clone of https://github.com/conda-forge/perl-storable-feedstock/pull/1

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please ping team

**Comment by martin-g** [comment]
@conda-forge/core Could someone please review and merge this PR? Thank you!

**Comment by xhochy** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Let's rerender and merge then.

**Comment by martin-g** [comment]
The linux_ppc64le has been cancelled at TravisCI. I will exclude ppc64le!

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@xhochy All looks good now!

**Pull request merged**
